name: ci-golang-workflow
on:
  pull_request:
    branches:
      - develop
jobs:
  check-aplication:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: 1.18
      - run: go test
      - run: go run math.go

      #gerando build da images do docker

      # instalando docker no runner do github
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build image
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: false
          tags: lucas6g/go-ci:latest
