name: ci-golang-workflow
on: [push]
jobs:
  check-aplication:
    runs-on: ubunto-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: 1.18
      - run: go test
      - run: go run math.go
